version: "2"

run:
  timeout: 5m
  concurrency: 4
  tests: true
  relative-path-mode: gomod
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - ineffassign
    - unused
    - misspell
    - gocritic
    - goconst
    - gocyclo
    - nakedret
    - unparam
    - prealloc
    - bodyclose
    - asasalint
    - makezero
    - nolintlint
    - dogsled
    - funlen
    - lll
    - nestif
    - whitespace
    - zerologlint
    - gochecknoinits
    - godox
    - mnd
    - goprintffuncname
    - decorder
    - errorlint
    - funcorder

  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
    decorder:
      # Required order of `const`, `var`, `type`and `func` declarations inside a file.
      dec-order:
        - const
        - var
        - type
        - func
    errcheck:
      # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
      # Such cases aren't reported by default.
      # Default: false
      check-type-assertions: true
      check-blank: false
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    lll:
      line-length: 140
      tab-width: 1
    funlen:
      lines: -1 # the number of lines (code + empty lines) is not a right metric and leads to code without empty line or one-liner.
      statements: 50
    misspell:
      locale: US
      ignore-rules:
        - "importas" # linter name
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - whyNoLint
    staticcheck:
      checks: ["all","-ST1000", "-ST1020"]
    mnd:
      # don't include the "operation" and "assign"
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
      ignored-functions:
        - strings.SplitN
    errorlint:
      asserts: false
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - mnd
          - lll
      - linters:
          - lll
        source: "^//go:generate "
      - linters:
          - errcheck
        text: "(\\*sql.Rows).Close"
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/centurypay/*
