linters-settings:  
  # Tool for detection of long functions
  funlen:
    lines: 120
    statements: 100
  
  # Finds repeated strings that could be replaced by a constant
  goconst:
    # minimal length of string constant, 3 by default
    min-len: 3
    # minimal occurrences count to trigger, 3 by default
    min-occurrences: 3
  
  # Provides diagnostics that check for bugs, performance and style issues.
  # Extensible without recompilation through dynamic rules.
  # Dynamic rules are written declaratively with AST patterns, filters, report message and optional suggestion.
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  # Computes and checks the cyclomatic complexity of functions
  gocyclo:
    min-complexity: 30
  

  # An analyzer to detect magic numbers.
  gomnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '10'
    ignored-functions:
      - 'math.*'
      - 'http.StatusText'
  
  # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
  govet:
    check-shadowing: true
  
  # Reports long lines
  lll:
    line-length: 180

  # Report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
  check-blank: true

  # Finds commonly misspelled English words in comments
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
    ignore-words:
  
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
  
  godot:
    # Comments to be checked: `declarations`, `toplevel`, or `all`.
    # Default: declarations
    scope: toplevel
    # List of regexps for excluding particular comment lines from check.
    # Default: []
    exclude:
      # Exclude todo and fixme comments.
      - "^fixme:"
      - "^todo:"
    # Check that each sentence ends with a period.
    # Default: true
    period: false
    # Check that each sentence starts with a capital letter.
    # Default: false
    capital: true      


linters:
  disable-all: true
  enable:
    - bodyclose
    # - depguard // temporarily disabled due to an issue in golangcilint latest version
    - dogsled
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - godot
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - sqlclosecheck
  
  # don't enable:
    # - dupl
    # - asciicheck
    # - scopelint
    # - gochecknoglobals
    # - gocognit
    # - godox
    # - goerr113
    # - interfacer
    # - maligned
    # - nestif
    # - prealloc
    # - testpackage
    # - revive
    # - wsl

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd

run:
  deadline: 5m
  skip-dirs:
    - vendor
