# this configuration is used by sqlboiler to generate models
no-tests = true

[mysql]
  dbname  = "go_boilerplate"
  host    = "localhost"
  port    = 1444
  user    = "go_boilerplate"
  pass    = "go_boilerplate"
  sslmode = "false"
  blacklist = [
    "migrations_app_go_boilerplate"
  ]
