name: PR Test Cases

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    name: Test Cases
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{github.event.pull_request.head.ref}}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.24.2

    - name: Test
      run: go test -v ./...

    - uses: act10ns/slack@v1
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: ${{ job.status }}
        config: .github/slack/config.yml
        channel: '#github-actions'
      if: failure()